docs(linux): Update 10.01 Issue Tracker
TexasInstruments/processor-sdk-doc pull request #110
Opened 2024-12-12 19:45 UTC by praneethbajjuri

Issues Resolved and Open are going to be reflecting thru https://sir.ext.ti.com system.

This fix is to cleanup references from past release and add a small note clarifying the direction.

2024-12-12 19:55 UTC, cshilwant requested changes
Since its legacy platform,

s/10.1/9.3 in commit message

2024-12-12 20:14 UTC, praneethbajjuri commented
Will send a followup PR with the Issue tracker section when all the new bugs resolved/closed are update in the sir system.

2024-12-12 20:17 UTC, cshilwant requested changes
For all note directives, code sections should clearly line up with directive
as mentioned in https://github.com/TexasInstruments/processor-sdk-doc/blob/master/CONTRIBUTING.md#indentation-and-whitespace

2024-12-12 20:19 UTC, cshilwant commented on source/devices/AM335X/linux/Release_Specific_Release_Notes.rst
> +    - Release Specific Issues including details will be published thru Software Incident Report (SIR) portal
```suggestion
    - Release Specific Issues including details will be published through Software Incident Report (SIR) portal
```
For all references of thru in PR,

https://www.grammarly.com/blog/commonly-confused-words/through-thru/#:~:text=Through%20is%20the%20only%20formally,%2Dthroughs%2Fdrive%2Dthrus.

2024-12-12 22:02 UTC, StaticRocket requested changes

2024-12-12 22:02 UTC, StaticRocket commented on source/devices/AM335X/linux/Release_Specific_Release_Notes.rst
> +.. note::
I don't think this should be a note if it's the expected location for the release bug report moving forward. It should just be a paragraph about where they can find this information and why. For example:


```rst
To unify software issue tracking, release specific issue tracking is currently
handled through the `Software Incident Report (SIR) portal
<https://sir.ext.ti.com/>`.
```

2024-12-12 22:57 UTC, StaticRocket commented on source/devices/AM335X/linux/Release_Specific_Release_Notes.rst
> +.. note::
Offline sync: This is not the permanent solution yet. We're fine with the note until a proper solution is determined.

2024-12-12 22:57 UTC, StaticRocket approved these changes

2024-12-13 01:02 UTC, cshilwant approved these changes

2024-12-13 01:05 UTC, merged