fix(PRU-ICSS): Remove the PRU-ICSS table that comes up on Sitara Legacy devices docs index page for now
TexasInstruments/processor-sdk-doc pull request #134
Opened 2024-12-17 12:57 UTC by jeevantelukula

Currently there was no support on these protocols, so remove from the docs index page until further clarity.

2024-12-17 13:09 UTC, cshilwant requested changes
@jeevantelukula Nitpick,

commit message title looks too long.

Checkout previous commits by other authors to get more idea - https://github.com/TexasInstruments/processor-sdk-doc/commits/master/
 
Also, I would personally encourage you to checkout - https://github.com/torvalds/linux/pull/17#issuecomment-5661185

2024-12-17 13:18 UTC, jsuhaas22 approved these changes

2024-12-17 13:22 UTC, cshilwant requested changes

2024-12-17 13:22 UTC, cshilwant commented on source/linux/Overview/_Processor_SDK_Linux_Software_Developers_Guide.rst
> +    .. ifconfig:: CONFIG_part_variant not in ('AM62X', 'AM62AX', 'AM62PX', 'AM335X', 'AM437X', 'AM65X')
@jeevantelukula You missed removing these sections from individual device toc tree? 

For Instance - https://software-dl.ti.com/processor-sdk-linux/esd/AM65X/09_03_05_02/exports/docs/linux/Industrial_Protocols.html shouldn't be visible in the device level toc tree

2024-12-17 13:52 UTC, cshilwant commented
@nsaulnier-ti @liubiin for reviews

2024-12-17 16:19 UTC, nsaulnier-ti commented
@jeevantelukula is PTP and RSTP still tested on CPSW for AM335x & AM437x?

If so, I would rather that we just remove CCLink & OPC/UA, and keep the PTP and RSTP pages. Just update the note at the top of the PTP page to say the information only applies to CPSW, instead of "only applies to CPSW on SDK 9.1"

2024-12-18 05:48 UTC, danish-ti commented
@nsaulnier-ti PTP / RSTP is not tested on CPSW in this release. AFAIK, it was last tested during 8.x SDK. Same is true for ICSSM as well. We are not doing any active testing on legacy platforms (except AM65x)

2024-12-18 08:43 UTC, jeevantelukula commented
> @nsaulnier-ti PTP / RSTP is not tested on CPSW in this release. AFAIK, it was last tested during 8.x SDK. Same is true for ICSSM as well. We are not doing any active testing on legacy platforms (except AM65x)

@nsaulnier-ti Since PTP/RSTP are not tested on CPSW also, I removed those pages along with CCLink & OPC/UA pages from 335x/437x docs. As there is active testing for AM65x platform, these sections are maintained in docs.

2024-12-19 18:26 UTC, nsaulnier-ti approved these changes

2024-12-19 18:28 UTC, cshilwant approved these changes

2024-12-20 03:24 UTC, cshilwant commented
@jsuhaas22 @paresh-bhagat12 for reviews

2024-12-20 03:42 UTC, jsuhaas22 approved these changes
LGTM

2024-12-20 04:36 UTC, merged