PREEMPT_RT latency performance for SDK 10.1
TexasInstruments/processor-sdk-doc pull request #137
Opened 2024-12-18 00:57 UTC by bryanbrattlof

Hello Everyone!

This small series updates the PREEMPT_RT latency performance numbers for the CoreSDK 10.1 release observed when using a simple CPU based background load.

Happy Hacking
~Bryan

2024-12-18 01:07 UTC, praneethbajjuri submitted a review, later dismissed

2024-12-18 01:15 UTC, praneethbajjuri commented
> New warnings found with rstcheck:
> ```text
> source/devices/AM64X/linux/RT_Linux_Performance_Guide.rst:502: (INFO/1) Duplicate implicit target name: "am64xx-evm".
> ```
> 

Address this warning

2024-12-18 04:01 UTC, StaticRocket requested changes
Content is fine. Just style issues.

2024-12-18 05:03 UTC, cshilwant submitted a review, later dismissed

2024-12-18 05:03 UTC, cshilwant commented on source/devices/AM62AX/linux/img/rt-cpu-method-all-latency-histogram.png
Any particular reasons for creating a new img directory, instead reusing https://github.com/TexasInstruments/processor-sdk-doc/tree/master/source/images

2024-12-18 05:03 UTC, cshilwant commented on source/devices/AM62PX/linux/img/rt-cpu-method-all-latency-histogram.png
Same comment as above

2024-12-18 05:03 UTC, cshilwant commented on source/devices/AM62X/linux/img/rt-cpu-method-all-latency-histogram.png
Same comment as above

2024-12-18 05:03 UTC, cshilwant commented on source/devices/AM64X/linux/img/rt-cpu-method-all-latency-histogram.png
Same comment as above

2024-12-18 05:06 UTC, bryanbrattlof commented on source/devices/AM62AX/linux/RT_Linux_Performance_Guide.rst
> +    cyclictest -m -Sp80 -D6h -h400 -i200 -M -q
ha I'll learn how to count one day

2024-12-18 05:11 UTC, bryanbrattlof commented on source/devices/AM62AX/linux/img/rt-cpu-method-all-latency-histogram.png
all of these images will be different for every platform. why would we want them in a general folder?

2024-12-18 05:11 UTC, bryanbrattlof commented on source/devices/AM62PX/linux/img/rt-cpu-method-all-latency-histogram.png
same as above

2024-12-18 05:11 UTC, bryanbrattlof commented on source/devices/AM62X/linux/img/rt-cpu-method-all-latency-histogram.png
same as above

2024-12-18 05:11 UTC, bryanbrattlof commented on source/devices/AM64X/linux/img/rt-cpu-method-all-latency-histogram.png
same as above

2024-12-18 14:55 UTC, StaticRocket requested changes

2024-12-18 14:55 UTC, StaticRocket commented on source/devices/AM64X/linux/RT_Linux_Performance_Guide.rst
> -AM64XX-EVM
This change causes a (valid) section depth jump error.

2024-12-18 19:01 UTC, cshilwant commented on source/devices/AM62AX/linux/img/rt-cpu-method-all-latency-histogram.png
@bryanbrattlof All images irrespective of device specific/ generic are all maintained under `source/images` and I have seen folks using SoC names as differentiator (which you will see it under source/images as well)

2024-12-19 05:35 UTC, praneethbajjuri approved these changes

2024-12-22 16:33 UTC, cshilwant approved these changes

2024-12-22 16:33 UTC, cshilwant commented
@StaticRocket / @DhruvaG2000 / @AashvijShenai for final review

2024-12-23 01:18 UTC, StaticRocket approved these changes
As much as I'd like to standardize asset locations, we have enough measures in place to prevent issues with people putting images and files near their RST source files. This is fine.

2024-12-23 01:25 UTC, merged