Android: Update known issues for SDK 10.1
TexasInstruments/processor-sdk-doc pull request #139
Opened 2024-12-18 09:35 UTC by makohoek

* Remove jack playback
* List U-Boot environment issue

@vishalmti @glaroque

2024-12-18 09:52 UTC, cshilwant commented on source/devices/AM62PX/android/Release_Specific_Release_Notes.rst
> +   * - **LCPD-42548**
@vishalmti Android will still follow non SIR bug IDs?

2024-12-18 10:40 UTC, makohoek commented on source/devices/AM62PX/android/Release_Specific_Release_Notes.rst
> +   * - **LCPD-42548**
From internal chat, quoting @vishalmti :

> Android JIRAs are not SIR system yet
> We cando that next release
> SITSW JIRA is used for Android
> If it's linux component, we use LCPD

2024-12-18 11:18 UTC, glaroque approved these changes

2024-12-18 12:43 UTC, praneethbajjuri submitted a review, later dismissed

2024-12-18 13:46 UTC, cshilwant approved these changes

2024-12-18 14:50 UTC, StaticRocket requested changes

2024-12-18 14:50 UTC, StaticRocket commented on source/devices/AM62X/android/Release_Specific_Release_Notes.rst
> +     - `969cb05aea9 <https://git.ti.com/cgit/ti-u-boot/ti-u-boot/commit/?id=969cb05aea9>`_
Nitpick: These links should be anonymous. (End in `__` instead of just `_`). You aren't referencing any of these keys later.

2024-12-18 16:01 UTC, makohoek commented
Change in v2:
- Use anonymous (`__`) links instead of referenced ones (`_`) (Randolph)

2024-12-18 18:18 UTC, cshilwant commented
> Change in v2:
> 
> * Use anonymous (`__`) links instead of referenced ones (`_`) (Randolph)

Thanks for following this methodology in docs as well. This helps in reviewing!

2024-12-18 18:18 UTC, cshilwant approved these changes

2024-12-18 18:18 UTC, merged

2024-12-19 08:40 UTC, makohoek commented
> Thanks for following this methodology in docs as well. This helps in reviewing!

I believe that helping the reviewers is very important. Doing a small "cover letter diff" as a comment does not take contributors too much time and should, imho, be standard practice.

Glad it helps :smile: