Update CODEOWNERS
TexasInstruments/processor-sdk-doc pull request #141
Opened 2024-12-18 10:49 UTC by VeeruPrudhvi

Adding self to the list of reviewers

2024-12-18 12:08 UTC, cshilwant requested changes
@VeeruPrudhvi `processor-sdk-doc` uses `commit-check-action` github action that follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for commit message.

Hence, we see the Commit Check GitHub workflow failing.
Checkout https://github.com/TexasInstruments/processor-sdk-doc/actions/runs/12391426830?pr=141 for more details

In your case, the commit message can be similar to https://github.com/TexasInstruments/processor-sdk-doc/pull/78/commits/56ca25b1189fe22d2b639e83ce72ebbeb7a77851 which is an accepted format & ensures that the workflow passes.

Also, ensure you Sign-off each commit by adding a `-s` flag with `git commit` - https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s

2024-12-19 06:15 UTC, jsuhaas22 submitted a review, later dismissed
LGTM

2024-12-19 06:15 UTC, jeevantelukula approved these changes

2024-12-19 08:35 UTC, DhruvaG2000 requested changes
I see a lot of unintended changes here due to some git mishap probably. Please no merge commits and no REVERT merge commits either. Just git pull --rebase on master and then ``force push`` to the PR branch.

2024-12-19 08:41 UTC, cshilwant requested changes

2024-12-19 08:41 UTC, cshilwant commented on .github/CODEOWNERS
Please plan to address https://github.com/TexasInstruments/processor-sdk-doc/pull/141#pullrequestreview-2513688632

2024-12-19 08:41 UTC, cshilwant requested changes
Please plan to address https://github.com/TexasInstruments/processor-sdk-doc/pull/141#pullrequestreview-2513688632

2024-12-19 09:26 UTC, closed without merging