feat(Snagfactory): Add a note for Fastboot buffer size
TexasInstruments/processor-sdk-doc pull request #146
Opened 2024-12-19 14:09 UTC by paresh-bhagat12

Snagfactory flashing will fail if fastboot buffer size is smaller than the file being flashed for non-sparse images. Add a note for the same.

2024-12-19 14:15 UTC, cshilwant requested changes

2024-12-19 14:15 UTC, cshilwant commented on source/linux/Foundational_Components/Tools/Flash_via_Fastboot.rst
> +   CONFIG_FASTBOOT_BUF_SIZE is defined in am6x_a53_snagfactory.config and specifies
```suggestion
   ``CONFIG_FASTBOOT_BUF_SIZE`` is defined in :file:`am6x_a53_snagfactory.config` and specifies
```

2024-12-19 14:15 UTC, cshilwant commented on source/linux/Foundational_Components/Tools/Flash_via_Fastboot.rst
Better to add a note mentioning that `python3 -m pip install --user snagboot` at the time of SDK 10.1 correspondence to Snagboot v2.0 release tag

2024-12-19 14:23 UTC, cshilwant approved these changes

2024-12-20 02:25 UTC, praneethbajjuri approved these changes

2024-12-20 03:16 UTC, merged