Updates Firmware Bugs Resolved in 10.01 Release
TexasInstruments/processor-sdk-doc pull request #148
Opened 2024-12-20 10:39 UTC by hm-ti

Issue Tracker Update containing details of Bugs Resolved and Bugs Open.

2024-12-20 13:45 UTC, praneethbajjuri reviewed
Need a better commitmsg informing what these bug category is to a minimum

2024-12-20 17:22 UTC, cshilwant commented
@n-moorthy-karunanithi for reviews

2024-12-22 11:59 UTC, cshilwant requested changes
https://github.com/TexasInstruments/processor-sdk-doc/pull/148#pullrequestreview-2517585198

2025-03-03 12:44 UTC, praneethbajjuri commented
@hm-ti is this still a open PR ?

2025-03-10 21:19 UTC, StaticRocket commented
Closing this. Way past merge window with no response.

2025-03-10 21:19 UTC, closed without merging