Bugfix/nbs
TexasInstruments/processor-sdk-doc pull request #36
Opened 2024-11-07 17:44 UTC by StaticRocket

Fix various style issues and odd character usage that may affect rst parsers.

2024-11-08 06:13 UTC, StaticRocket commented
Huh. So it appears that rstcheck doesn't know how to parse the standard substitution lists.

2024-11-10 03:46 UTC, StaticRocket commented
This PR now upgrades rstcheck to a version that can actually parse standard include directives.

2024-11-10 12:21 UTC, cshilwant submitted a review, later dismissed

2024-11-10 12:22 UTC, cshilwant commented
> New warnings found with rstcheck:
> 
> ```
> [Errno 2] No such file or directory: 'g++'
> ```

@StaticRocket Why does it hunts for g++?

2024-11-10 18:10 UTC, StaticRocket commented
It's part of the code block checking. It uses GCC to check if a code block is actually valid C, if it's been tagged as C.

Unfortunately most of our code blocks are just snippets with invalid syntax like lines of `...` in between valid lines so I just disable those checks.

If you see the commit log, one commit changes this config file key since the newer version of rstcheck doesn't use that key.

The new config was picked up by the old workflow so it brings this error up.

2024-11-29 07:02 UTC, cshilwant requested changes
![image](https://github.com/user-attachments/assets/132242d9-039d-4f21-8fc1-4483c5546c3e)

2024-11-29 07:04 UTC, StaticRocket commented
You know what, let me split this PR. Package upgrades should be independent of this.

2024-11-29 21:48 UTC, StaticRocket commented
Will rebase this once #61 is merged. This will make the CI checks happy.

2025-01-15 05:31 UTC, cshilwant requested changes
Resolve merge conflicts

2025-01-20 04:23 UTC, AashvijShenai approved these changes

2025-01-20 05:10 UTC, cshilwant approved these changes

2025-01-20 05:45 UTC, Siddharth-Vadapalli-at-TI approved these changes

2025-01-20 05:59 UTC, jeevantelukula approved these changes

2025-01-20 07:11 UTC, merged