fix: Updated the CSI2RX SDK documentation
TexasInstruments/processor-sdk-doc pull request #43
Opened 2024-11-19 12:01 UTC by Yemike-Abhilash-Chandra

Added CSI2RX testing details specifying various combinations of sensors tested across boards.

signed-off-by: Yemike Abhilash Chandra y-abhilashchandra@ti.com

2024-11-20 07:20 UTC, vaishnavachath approved these changes

2024-11-20 07:50 UTC, uditkumarti submitted a review, later dismissed

2024-11-20 09:38 UTC, cshilwant approved these changes

2024-11-20 23:27 UTC, StaticRocket requested changes

2024-11-20 23:27 UTC, StaticRocket commented on source/linux/Foundational_Components/Kernel/Kernel_Drivers/Camera/CSI2RX.rst
> +            +--------------+---------------------------------------+-----------------------------------+
```suggestion
        +--------------+---------------------------------------+-----------------------------------+
        | Hardware     | Sensor                                | Default format and resolution     |
        +==============+=======================================+===================================+
        | J722S        | OV5640 TEVI/PCAM Rpi Module           | YUYV8_1X16/1280x720 at 30 fps     |
        +--------------+---------------------------------------+-----------------------------------+
        | J722S        | FPDLink fusion 1 EVM, IMX390          | SRGGB12_1X12/1936x1100 at 30 fps  |
        +--------------+---------------------------------------+-----------------------------------+
        | J722S        | IMX219 RPi Camera                     | SRGGB8_1X8/1920x1080 at 30 fps    |
        +--------------+---------------------------------------+-----------------------------------+
```

2024-11-20 23:27 UTC, StaticRocket commented on source/linux/Foundational_Components/Kernel/Kernel_Drivers/Camera/CSI2RX.rst
> +
```suggestion
        +--------------+---------------------------------------+-----------------------------------+
        | Hardware     | Sensor                                | Default format and resolution     |
        +==============+=======================================+===================================+
        | J784S4       | LI OV5640 MIPI CSI Camera             | YUYV8_1X16/1280x720 at 30 fps     |
        +--------------+---------------------------------------+-----------------------------------+
        | J784S4       | FPDLink fusion 1 EVM, IMX390          | SRGGB12_1X12/1936x1100 at 30 fps  |
        +--------------+---------------------------------------+-----------------------------------+
        | AM69A        | IMX219 RPi Camera                     | SRGGB8_1X8/1920x1080 at 30 fps    |
        +--------------+---------------------------------------+-----------------------------------+
        | AM69A        | LI OV5640 MIPI CSI Camera             | YUYV8_1X16/1280x720 at 30 fps     |
        +--------------+---------------------------------------+-----------------------------------+
        | AM69A        | FPDLink fusion 1 EVM, IMX390          | SRGGB12_1X12/1936x1100 at 30 fps  |
        +--------------+---------------------------------------+-----------------------------------+
        | J742S2       | FPDLink fusion 1 EVM, IMX390          | SRGGB12_1X12/1936x1100 at 30 fps  |
        +--------------+---------------------------------------+-----------------------------------+
```

2024-11-20 23:27 UTC, StaticRocket commented on source/linux/Foundational_Components/Kernel/Kernel_Drivers/Camera/CSI2RX.rst
> +            +--------------+---------------------------------------+-----------------------------------+
```suggestion
        +--------------+---------------------------------------+-----------------------------------+
        | Hardware     | Sensor                                | Default format and resolution     |
        +==============+=======================================+===================================+
        | J721S2       | LI OV5640 MIPI CSI Camera             | YUYV8_1X16/1280x720 at 30 fps     |
        +--------------+---------------------------------------+-----------------------------------+
        | J721S2       | FPDLink fusion 1 EVM, IMX390          | SRGGB12_1X12/1936x1100 at 30 fps  |
        +--------------+---------------------------------------+-----------------------------------+
        | AM68A        | IMX219 RPi Camera                     | SRGGB8_1X8/1920x1080 at 30 fps    |
        +--------------+---------------------------------------+-----------------------------------+
        | AM68A        | LI OV5640 MIPI CSI Camera             | YUYV8_1X16/1280x720 at 30 fps     |
        +--------------+---------------------------------------+-----------------------------------+
        | AM68A        | FPDLink fusion 1 EVM, IMX390          | SRGGB12_1X12/1936x1100 at 30 fps  |
        +--------------+---------------------------------------+-----------------------------------+
```

2024-11-20 23:27 UTC, StaticRocket commented on source/linux/Foundational_Components/Kernel/Kernel_Drivers/Camera/CSI2RX.rst
> +
```suggestion
        +--------------+---------------------------------------+-----------------------------------+
        | Hardware     | Sensor                                | Default format and resolution     |
        +==============+=======================================+===================================+
        | J721E EVM    | LI OV5640 MIPI CSI Camera             | YUYV8_1X16/1280x720 at 30 fps     |
        +--------------+---------------------------------------+-----------------------------------+
        | J721E EVM    | FPDLink fusion 1 EVM, IMX390          | SRGGB12_1X12/1936x1100 at 30 fps  |
        +--------------+---------------------------------------+-----------------------------------+
        | J721E SK     | IMX219 RPi Camera                     | SRGGB8_1X8/1920x1080 at 30 fps    |
        +--------------+---------------------------------------+-----------------------------------+
        | J721E SK     | LI OV5640 MIPI CSI Camera             | YUYV8_1X16/1280x720 at 30 fps     |
        +--------------+---------------------------------------+-----------------------------------+
        | J721E SK     | FPDLink fusion 1 EVM, IMX390          | SRGGB12_1X12/1936x1100 at 30 fps  |
        +--------------+---------------------------------------+-----------------------------------+
```

2024-11-21 05:19 UTC, Yemike-Abhilash-Chandra commented
@StaticRocket  I have made the changes as per your request. Kindly review and approve the PR if there are no other suggestions.

2024-11-21 07:22 UTC, StaticRocket approved these changes

2024-11-21 16:55 UTC, uditkumarti approved these changes

2024-11-21 16:58 UTC, praneethbajjuri approved these changes

2024-11-21 17:31 UTC, merged

2024-11-22 08:36 UTC, devarsht commented on source/linux/Foundational_Components/Kernel/Kernel_Drivers/Camera/CSI2RX.rst
> +    CSI2RX testing details
I would prefer to headline it as Supported CSI2x sensors instead of testing details.