J7_Family: Linux: Update PCIe-ETH performance for SDK 10.01
TexasInstruments/processor-sdk-doc pull request #58
Opened 2024-11-28 07:54 UTC by Siddharth-Vadapalli-at-TI

Document the unidirectional TCP throughput with different packet sizes for Ethernet over PCIe with Linux corresponding to SDK 10.01 on J7 devices.

2024-11-28 13:43 UTC, cshilwant requested changes
Checkout https://github.com/TexasInstruments/processor-sdk-doc/actions/runs/12064682089?pr=58 for errors reported by commit check workflow.

Refer CONTRIBUTING guidelines for more details - https://github.com/TexasInstruments/processor-sdk-doc/blob/master/CONTRIBUTING.md

2024-11-29 06:19 UTC, StaticRocket commented
You are correct. That is not specifically relevant to this PR. Some include file in this project is bugged and it causes errors to propagate through the global replacevars include file. I have a PR to drop this at some point.

2024-11-29 06:20 UTC, StaticRocket approved these changes

2024-11-29 07:00 UTC, cshilwant approved these changes
rst syntax looks fine, will let @uditkumarti / @aniket-l to verify the performance numbers captured & integrate the PR

2024-12-02 09:44 UTC, uditkumarti approved these changes

2024-12-02 22:03 UTC, merged