AM62x: Add minimal platform board port guide
TexasInstruments/processor-sdk-doc pull request #9
Opened 2024-10-18 17:35 UTC by praneethbajjuri

This reverts commit ef600ddd3fb335f745ac179f15eb0526ea2a6418.

https://www.ti.com/lit/pdf/spradd1 is now published.
Enable back the minimal platform board porting guide for AM62x.

2024-10-18 22:05 UTC, cshilwant submitted a review, later dismissed
LGTM

2024-10-18 22:43 UTC, StaticRocket requested changes
Do not use `.rst.inc`. This confuses lexers. Please use the `_<Name>.rst` convention for rst files intended to be included by other files.

2024-10-28 14:26 UTC, nmenon commented
rebase on master to get the checkers to run

2024-11-08 20:00 UTC, StaticRocket requested changes

2024-11-08 20:00 UTC, StaticRocket commented on source/common/Tools/Minimal_Platform_Development.rst.inc
Just remove this file and inject the contents directly into `source/linux/How_to_Guides/Host/Minimal_Platform_Development.rst`

I do not see a reason to make this a separate file when only one file includes it and that file's only content is the aforementioned include directive.

2024-12-09 19:58 UTC, StaticRocket requested changes
Original feedback not addressed. Commits break contribution guidelines.

2024-12-17 21:47 UTC, praneethbajjuri commented
> Original feedback not addressed. Commits break contribution guidelines.

addressed. Please review @StaticRocket

2024-12-17 21:59 UTC, StaticRocket approved these changes

2024-12-17 22:52 UTC, vishalmti approved these changes

2024-12-18 01:01 UTC, bryanbrattlof approved these changes
Nice! Thanks @praneethbajjuri

2024-12-18 04:15 UTC, cshilwant approved these changes

2024-12-18 04:15 UTC, merged

2024-12-19 00:07 UTC, jmenti reviewed
Nice, ack