fix: Update the Yocto configuration file for J7200 Linux SDK
TexasInstruments/processor-sdk-doc pull request #98
Opened 2024-12-11 13:37 UTC by aniket-l

J7200 Linux SDK's yocto config file differs from that of AM67/AM68/AM69.

2024-12-11 15:43 UTC, cshilwant approved these changes

2024-12-11 17:59 UTC, StaticRocket commented on source/devices/J7_Family/linux/Release_Specific_Yocto_layer_Configuration.rst
> +
Agreed. Already got a few people internally asking about this change, why it was done, etc.

Doubt anyone outside of TI will have a clue why this platform is different.

2024-12-12 11:25 UTC, aniket-l commented on source/devices/J7_Family/linux/Release_Specific_Yocto_layer_Configuration.rst
> +
Okay will update commit msg

2024-12-14 17:20 UTC, cshilwant requested changes
https://github.com/TexasInstruments/processor-sdk-doc/pull/98#discussion_r1881885763

https://github.com/TexasInstruments/processor-sdk-doc/pull/98#discussion_r1880511496

2024-12-22 12:00 UTC, cshilwant commented
@aniket-l are you still planning to update this PR?
(As J7 releases are already out)

2025-02-13 11:53 UTC, praneethbajjuri commented on source/devices/J7_Family/linux/Release_Specific_Yocto_layer_Configuration.rst
@aniket-l  can you comment and close on this dependency .
Please clarify if https://software-dl.ti.com/jacinto7/esd/processor-sdk-linux-j7200/10_01_08_01/exports/docs/devices/J7_Family/linux/Release_Specific_Release_Notes.html is generated based on this docs project

2025-04-09 22:04 UTC, StaticRocket commented
Closing due to inactivity. Reopen if this ever gets modified.

2025-04-09 22:04 UTC, closed without merging